version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "demo_db"
    ports:
      - "5434:5432"
